# Generated by Django 5.2.11 on 2026-02-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_idempotencyrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_family__c6d975_idx',
            old_name='events_event_family__b55af7_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_event_t_d1af98_idx',
            old_name='events_event_event_ty_d0fe1a_idx',
        ),
    ]
