# Generated by Django 5.2.11 on 2026-02-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='familymembership',
            new_name='families_fa_user_id_fc0662_idx',
            old_name='families_fam_user_id_50b8fc_idx',
        ),
    ]
